baseURL = "https://www.janraasch.com/"
languageCode = "en-US"
title = "Jan Raasch, web developer building software for product value ğŸš€"
theme="hugo-bearblog"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

# Copyright
copyright = "<a href='/imprint'>&copy;2020 Jan Raasch - Imprint & Privacy Policy</a>"

[params]

  # Metadata for search engines and social sharing
  author = "Jan Raasch"
  description = "Homepage of Jan Raasch: Software developer, product enthusiast & yoga teacher ğŸ§˜ğŸ»â€â™€ï¸"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Jan Raasch - Software Developer & Yoga Teacher ğŸ§˜ğŸ»â€â™€ï¸"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/default/share.png"]

  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  site_manifest = "images/default/site.webmanifest"

  [params.meta]
    keywords = "freelancer, remote, lÃ¼beck, germany, hamburg, software, software development, consulting, product thinker, lead developer, yoga, yoga teacher, yoga courses, personal training"

  [params.favicon]
    # Generated with https://favicon.io/favicon-generator/?t=ğŸ‘¨ğŸ¼&ff=Leckerli+One&fs=260&fc=%230A0&b=rounded&bc=transparent
    default = "images/default/favicon-32x32.png"
    apple_touch_icon = "images/default/apple-touch-icon.png"
    thirtytwo = "images/default/favicon-32x32.png"
    sixteen = "images/default/favicon-16x16.png"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
